DROP TRIGGER IF EXISTS posts_au;
DROP TRIGGER IF EXISTS posts_ad;
DROP TRIGGER IF EXISTS posts_ai;
DROP TABLE IF EXISTS posts_fts;
DROP TABLE IF EXISTS scrape_log;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS sources;
